stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "djangodocker"
  IMAGE_TAG: "$CI_COMMIT_REF_NAME"

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG .

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
    - docker logout $CI_REGISTRY
